<?php
include_once "Views/pageElements/Header.phtml";
if(!isset($_SESSION['user_id'])){
    echo  '<meta http-equiv="refresh"
   content="0; url=index.php">';
}
if (isset($view->warningMessage)) {
    include "Modals/WarningModal.phtml";
    echo "<script>$('#warningModal').modal('show')</script>";
}
?>

<div class="row">
    <div class="col">
        <div class="centered-container">
            <form class="mt-5" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>" enctype="multipart/form-data">
                <h1 class="page-title text-center mt-3">What do you want to include in your post?</h1>
                <div class="mt-3">
                    <label>Title</label>
                    <div class="input-group ">
                        <input type="text" name="postTitle" class="form-control"
                               aria-describedby="inputGroup-sizing-default">
                    </div>
                </div>

                <div class="form-group mt-3">
                    <label for="postCategorySelector">Select Category</label>
                    <select class="form-control" name="postCategory" id="postCategorySelector">
                        <?php
                        foreach ($view->categories as $category) {
                            echo '<option>' . $category . '</option>';
                        }
                        ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="postContent">Enter some text</label>
                    <textarea id="postContent" class="form-control text-area" name="postContent"></textarea>
                </div>

                <div class="mt-3 form-group">
                    <label>Post picture</label>
                    <div class="custom-file mt-2">
                        <input type="file" name="fileToUpload" id="fileToUpload">
                    </div>
                </div>
                <div class="mt-3 form-group">
                    <img src="Data/Captcha.php" alt=""/>
                    <div>
                        <input type="text" name="captchaValueEntered"/>
                    </div>
                </div>
                <button type="submit" name="addPostButton" class="btn btn-primary mt-3">Add post</button>
            </form>
        </div>

    </div>
</div>


</div>
</body>
</html>
