<?php include "Views/pageElements/Header.phtml";
require_once "Modals/WriteReviewModal.phtml";
$currentPost = $view->currentPost;
$currentPostComments = $view->currentPostComments;

?>
<div class="centered-container mt-4 mb-5">

    <h1> <?php echo $currentPost->getPostTitle() ?></h1>
    <img src="<?php echo $currentPost->getPostImage() ?>" class="image-post-opened">
    <p class="post-text mt-5"> <?php echo $currentPost->getPostContent(); ?> </p>
    <?php
     //check if the user is logged in and if the post belong to him
    if ($view->isUserLoggedIn && !$view->postBelongsToUser) {
        if ($currentPost->getIsFavorite() == false ) {
            //if the user is logged in but the post is not added to favorite
            ?>
            <form action="CurrentPost.php" method="post">
                <button type="submit" class="btn btn-primary btn" name="addToFavoriteButton">Add to favorites</button>
            </form>
            <?php
        }
    }
    ?>
    <div class="comments-area mt-5">
        <h2>Comments</h2>
        <?php

        foreach ($currentPostComments as $comment) {
            ?>
            <div class="comment card">
                <div class="comment-body">
                    <span><?php echo $comment->getAuthor() ?></span>
                    <p><?php echo $comment->getCommentText(); ?></p>
                </div>
            </div>
            <?php
        }
        if ($view->isUserLoggedIn){
        ?>
        <button type="button" class="btn btn-primary btn" data-toggle="modal" data-target="#writeReviewModal">Write
            comment
        </button>
    </div>
<?php
}
?>

</div>