<?php require "Header.phtml";

?>
<div class="centered-container mt-4">

    <h1> <?php $extendedPost->getPostTitle() ?></h1>;
    <img src="images/ <?php $extendedPost->getPostImage()?>" class="image-post">';
    <p class="post-text"> <?php $extendedPost->getPostContent()?> </p>

    <h2>Comments</h2>
    <div class="comments-area">

        <div class="comment card">
            <div class="comment-body">
                <h3>Simple man</h3>
                <p>This is a simple text from a simple man</p>
            </div>
        </div>
        <div class="comment card">
            <div class="comment-body">
                <h3>Simple man</h3>
                <p>This is a simple text from a simple man</p>
            </div>
        </div>
        <div class="comment card">
            <div class="comment-body">
                <h3>Simple man</h3>
                <p>This is a simple text from a simple man</p>
            </div>
        </div>

        <button type="submit" class="btn btn-primary btn-block btn-lg" name="writeReview">Write review</button>
    </div>

</div>