<?php
include "Views/pageElements/Header.phtml";
if (!isset($_SESSION['user_id'])) {
    echo '<meta http-equiv="refresh"
   content="0; url=index.php">';
}
$friends = $view->friends;
?>
<h3 class="text-center">Pending requests</h3>
<?php
if (sizeof($view->friendRequests) > 0) {
    foreach ($view->friendRequests as $friendRequest) {
        $view->friendRequest = $friendRequest;
        ?>
        <div class="row">
            <div class="col">
                <?php
                 include "Views/commonLayouts/FriendRequestLayout.phtml";
                ?>
            </div>

        </div>
        <?php
    }
} else {
    ?>
    <div class="alert alert-warning mt-3" role="alert">
        You do not have any friend requests
    </div>
    <?php
}
?>

<h3 class="text-center">Friends</h3>
<?php
if (sizeof($friends) != 0) {
    foreach ($friends as $friend) {
        $view->friend = $friend;
        ?>
        <div class="row mt-3">
            <div class="col">
                <?php
                include "FriendCard.phtml";
                ?>
            </div>
        </div>
        <?php
    }
} else {
    ?>
    <div class="alert alert-warning mt-3" role="alert">
        You do not have any friends yet
    </div>
    <?php
}
?>

</div>
</body>
</html>