<?php
include "Views/pageElements/Header.phtml";
include "Modals/WriteReviewModal.phtml";
$friends = $view->friends;
?>

<?php
     if(sizeof($friends)!=0) {
         foreach ($friends as $friend) {
             $view->friend = $friend;
             ?>
             <div class="row mt-3">
                 <div class="col">
                     <?php
                     include "FriendCard.phtml";
                     ?>
                 </div>
             </div>
             <?php
         }
     }else{
         ?>
        <div class="alert alert-warning mt-3" role="alert">
        You do not have any friends yet
        </div>
        <?php
    }
?>

</div>
</body>
</html>