<?php
include "Views/pageElements/Header.phtml";
include "Views/commonLayouts/SearchForm.phtml";

?>

<div class="row mt-5" xmlns="http://www.w3.org/1999/html">

    <div class="col">
        <?php
        foreach ($view->posts as $post) {
            $view->post = $post;
            include "PostCard.phtml";
        }
        ?>
    </div>
    <?php
    if (isset($_SESSION['user_id'])) {

        ?>

        <div id="friends-list" class="text-center">
            <div id="header-friends-list" onclick="toggleElement(document.getElementById('friends-list-body'))">
                <p>Friends</p>
            </div>
            <div id="friends-list-body">
                <div class="mt-3 mb-3" style="padding: 8px">
                    <input class="form-control mr-sm-2" autocomplete="off"
                           placeholder="Search for new people"
                           name="search-text"
                           aria-label="Search"
                           id="friends-search-field"
                           onkeyup="fetchFriendsSuggestions(event, this.value)"
                    >
                </div>
                <?php
                if (isset($view->friends)) {
                    ?>
                    <div id="friend-container">
                        <?php
                        /**
                         * @var User $friend
                         */
                        foreach ($view->friends as $friend) {
                            //todo
                            //here
                            ?>
                            <div id="friend_container_<?php echo $friend->getUserId() ?>" >
                                <button class="link-button"
                                        onclick="startChat('<?php echo $friend->getUserId() ?>','<?php echo $friend->getUsername() ?>')"><?php echo $friend->getUsername() ?>
                                </button>
                            </div>
                            <?php
                        }
                        ?>
                    </div>
                    <?php
                }
                ?>
                <div id="friends-suggestions-container">

                </div>
            </div>
        </div>

        <?php
    }
    ?>
</div>

<?php

//only show the add post button if the user is logged in
if ($view->isUserLoggedIn) {

    ?>
    <div data-toggle="modal" data-target="#addPostModal" class="add-post-button"><i class="fa fa-plus "></i>
    </div>
    <?php
}
?>
<form method="get" action="<?php echo $_SERVER['PHP_SELF']; ?>">
    <div class="row mt-4 ">
        <div class="col text-center">
            <input type="hidden" name="currentPageId" value="<?php echo md5($view->currentPage) ?>">
            <!--Make sure that the previous button is disabled if we are on the first page-->
            <button type="submit" name="previousPage"
                    class="btn btn-primary" <?php if ($view->currentPage == 1) echo 'disabled' ?>>Previous page
            </button>
            <!--Make sure that the next button is disabled if we are on the last page-->
            <button type="submit" name="nextPage"
                    class="btn btn-primary" <?php if ($view->currentPage == $view->numberOfPages) echo 'disabled' ?> >
                Next page
            </button>
        </div>
    </div>
</form>

<audio id="notificationAudio">
    <source src="sounds/test_notification.mp3" type="audio/mpeg">
</audio>
</div>

<?php
if (isset($_SESSION['user_id'])) {
    ?>
    <script src='Javascript/ChatManager.js'></script>
    <script> sessionUserId = '<?php echo $_SESSION['user_id'];?>'
        setIntervalNewMessages();
        checkHasUnreadMessages();
    </script>
    <?php
    include_once "Modals/AddPostModal.phtml";
}
?>
<script src="Javascript/AddPost.js"></script>
</body>
</html>


