<?php
include "Views/pageElements/Header.phtml";
?>
<link rel="stylesheet" href="css/learn.css">

<div class="row" xmlns="http://www.w3.org/1999/html">
    <div class="col">
        <h1 class="page-title text-center mb-3">Here are some recent posts</h1>
        <?php
        foreach ($view->posts as $post) {
            $view->post = $post;
            include "PostCard.phtml";
        }
        ?>
    </div>
</div>
<section id="article-menu">
    <?php
    foreach ($view->friends as $friend) {

        ?>
        <div>
            <a href="#" onclick="startChat()"><?php echo $friend->getUsername() ?></a>
        </div>
        <?php
    }
    ?>
    <script src="javascript/PageManager.js"></script>
</section>

<!--    <div id="message-window" style="position:fixed;bottom: 10px;width: 20%;right:18%;background: #EBE2E2;">-->
<!--        <div style=" background: #007BFF" onclick="-->
<!--          let messageBody = document.getElementById('message-window-body');-->
<!---->
<!--          if(messageBody.style.display === 'block'){-->
<!--             messageBody.style.display = 'none';-->
<!--          }else{-->
<!--              messageBody.style.display = 'block';-->
<!--          }-->
<!--        ">-->
<!--            <p class="text-center" style="color: white">Nela Ion</p>-->
<!--        </div>-->
<!--        <div id="message-window-body">-->
<!--            <div style="overflow:auto;height: 40vh">-->
<!--                -->
<!--            </div>-->
<!--            <div style="display: flex;">-->
<!--                <textarea style=" width: 100%;" type="text" id="messageField"></textarea>-->
<!--                <button style="background:#007BFF;color: white" onclick="sendMessage()"><i-->
<!--                            class="far fa-paper-plane"></i></button>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    <script src="Data/MessageManager.js"></script>-->



<?php
//only show the add post button if the user is logged in
if ($view->isUserLoggedIn) {
    ?>
    <a href="AddPost.php">
        <div class="float"><i class="fa fa-plus add-button"></i></div>
    </a>
    <?php
}
?>
<form method="get" action="<?php echo $_SERVER['PHP_SELF']; ?>">
    <div class="row mt-4 ">
        <div class="col text-center">
            <input type="hidden" name="currentPageId" value="<?php echo md5($view->currentPage) ?>">
            <!--Make sure that the previous button is disabled if we are on the first page-->
            <button type="submit" name="previousPage"
                    class="btn btn-primary" <?php if ($view->currentPage == 1) echo 'disabled' ?>>Previous page
            </button>
            <!--Make sure that the next button is disabled if we are on the last page-->
            <button type="submit" name="nextPage"
                    class="btn btn-primary" <?php if ($view->currentPage == $view->numberOfPages) echo 'disabled' ?> >
                Next page
            </button>
        </div>
    </div>
</form>

</div>
</body>
</html>


