<?php include "Views/pageElements/Header.phtml";
if (isset($_SESSION['user_id'])) {
    echo '<meta http-equiv="refresh"
   content="0; url=index.php">';
}
?>
<form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>" onsubmit="return robotTestPassed ">
    <div class="container-form">
        <div class="form-group">
            <label for="inputEmailLogin">Email address</label>
            <input type="email" class="form-control" id="inputEmailLogin" aria-describedby="emailHelp"
                   name="emailSignIn" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
            <label for="inputPasswordLogin">Password</label>
            <input name="passwordSignIn" type="password" class="form-control" id="inputPasswordLogin"
                   placeholder="Password">
        </div>
        <?php
           include "Views/commonLayouts/GoogleCaptcha.html";
        ?>
        <button type="submit" class="btn btn-primary" name="loginButton"  disabled>Log in</button>
        <?php if (isset($view->errorMessage)) {

            ?>
            <div class="alert alert-danger mt-3" role="alert">
                <?php echo $view->errorMessage ?>
            </div>

            <?php
        }
        ?>
    </div>
    <script>
        var robotTestPassed = false;
        function enableButton() {
            robotTestPassed = true;
            document.getElementsByClassName("submitButton")[0].disabled = false;
        }</script>
</form>

</div>

</body>

</html>