<?php
include "Views/pageElements/Header.phtml";
if (!isset($_SESSION['user_id'])) {
    echo '<meta http-equiv="refresh"
   content="0; url=index.php">';
}
$myPosts = $view->myPosts;
?>
<div class="row">
    <div class="col">
        <?php
        foreach ($myPosts as $post) {
            $view->post = $post;
            include "Views/PostCard.phtml";
        } ?>
    </div>
</div>

<?php
if (sizeof($myPosts) == 0) { ?>
    <div class="alert alert-warning mt-3" role="alert">
        You do not have any posts on the forum. Go to the main page and create one.
    </div>
    <?php
}
?>

</div>
</body>
</html>
