<?php
$post = $view->post;
?>
<div class="card mt-3 p-3">
    <div>
        <h3 class="card-title text-primary">  <?php echo $post->getPostTitle() ?></h3>
        <?php
        //if the user is logged in and the post belongs to him
        //let him him edit the post no matter where in the forum
        if (isset($_SESSION['user_id']) && Functions::encodeWithSha512($_SESSION['user_id']) === $post->getAuthorID()) {
            ?>
            <form method="get" action="EditPost.php" class="float-right">
                <button class="icon-button" type="submit"><i class="edit-icon"></i></button>
                <input type="hidden" name="valuePostID" value="<?php
                //it is better for security if we encrypt the post id, so
                // users cannot change it in the inspector
               echo $post->getPostID() ?>">
            </form>
            <?php
        }
        ?>
    </div>
    <?php
    if (isset($_SESSION['user_id'])) {
        ?>
        <form method="get" action="ProfilePage.php">

            <button type="submit" class="link-button" name="profileButton">Author
                : <?php echo $post->getAuthorName() ?></button>
            <input type="hidden" name="authorIDValue" value="<?php echo $post->getAuthorID() ?>">

        </form>
        <?php
    } else {
        ?>
        <span>Author: <?php echo $post->getAuthorName() ?></span>
        <?php
    }
    ?>
    <div>
        <span>Posted on : <?php echo $post->getPostDate() ?></span>
    </div>

    <img src="<?php
    if (isset($_SESSION['user_id'])) {
        echo $post->getPostImage();
    } else {
        echo "images/posts/image_not_logged_in.png";
    }

    ?>" class="card-img-top card-image" alt="">

    <div class="card-body">
        <p class="card-text"> <?php echo $post->getPostContent() ?></p>
        <form action="CurrentPost.php" method="get">
            <button type="submit" class="btn btn-primary" name="OpenPostButton">See post</button>
            <input type="hidden" name="valuePostID" value="<?php
            //it is better for security if we encrypt the post id, so
            // users cannot change it in the inspector
            echo $post->getPostID()?>">
        </form>
        <?php
        //only show the remove from favorite button if the post is added to favorites
        //we don't want to show this button on specific pages such as the home page
        if (isset($view->displayRemoveButton)) {

            ?>
            <!--The method post should point to the php script in which it was called-->
            <!-- Different php files have different implementation of this call
                 In the Favorites.php files once the user presses this button, the post will
                 be removed from favorites
            -->
            <form method="post">
                <button type="submit" class="btn btn-danger mt-3" name="removeButton">Remove</button>
                <input type="hidden" name="removeValue" value="<?php echo $post->getPostID() ?>">
            </form>

            <?php
        }
        ?>
    </div>
</div>


