<?php
/**
 * @var Post $post
 */

$post = $view->post;
?>

<div class="card mt-3 p-3">
    <div>
        <h3 class="card-title"
            onclick="window.location.href ='CurrentPost.php?valuePostID=' + '<?php echo Functions::encodeWithSha512($post->getPostID()) ?>'"> <?php echo $post->getPostTitle() ?></h3>
        <?php
        if (isset($_SESSION['user_id'])) {
            ?>
            <form method="get" action="ProfilePage.php" style="display:inline">
                <input type="image"
                       src="<?php echo $post->getUser()->getProfilePicture(100) ?>"
                       class="thumbnail-image">
                <input type="hidden" name="authorIDValue"
                       value="<?php echo Functions::encodeWithSha512($post->getUser()->getUserId()) ?>">
            </form>
            <?php
        }
        ?>

    </div>

    <div>
        <span>Posted on : <?php echo Functions::formatDate($post->getPostDate()) ?></span>
        <p class="card-text"> <?php echo substr($post->getPostContent(), 0, 200) ?></p>
    </div>


    <img src="<?php echo $post->getPostImage() ?>"
         onclick="window.location.href ='CurrentPost.php?valuePostID=' + '<?php echo Functions::encodeWithSha512($post->getPostID()) ?>'"
         class="card-img-top card-image">

    <div>
        <?php
        //only show the remove from favorite button if the post is added to favorites
        //we don't want to show this button on specific pages such as the home page
        if (isset($view->displayRemoveButton)) {

            ?>
            <!--The method post should point to the php script in which it was called-->
            <!-- Different php files have different implementation of this call
                 In the Favorites.php files once the user presses this button, the post will
                 be removed from favorites
            -->
            <form method="post">
                <button type="submit" class="btn btn-danger mt-3" name="removeButton">Remove</button>
                <input type="hidden" name="removeValue"
                       value="<?php echo Functions::encodeWithSha512($post->getPostID()) ?>">
            </form>

            <?php
        }
        ?>
    </div>

    <?php
    //if the user is logged in and the post belongs to him
    //let him him edit the post no matter where in the forum

    if (isset($_SESSION['user_id']) && $_SESSION['user_id'] === $post->getUser()->getUserId()) {
        ?>
        <form method="get" action="EditPost.php" class="float-right mt-4">
            <button class="btn btn-primary" type="submit">Edit</button>
            <input type="hidden" name="valuePostID" value="<?php
            //it is better for security if we encrypt the post id, so
            // users cannot change it in the inspector
            echo Functions::encodeWithSha512($post->getPostID()) ?>">
        </form>
        <?php
    }
    ?>

</div>


