<?php
include_once "Views/pageElements/Header.phtml";
/**
 * @var User $currentUser
 */
$currentUser = null;
if (isset($view->currentUser)) {
    $currentUser = $view->currentUser;
}

if (isset($view->warningMessage)) {
    include_once "Modals/WarningModal.phtml";
    echo "<script>$('#warningModal').modal('show')</script>";
}

if ($currentUser !== null) {
    $userPosts = $view->userPosts;
    ?>
    <div class="row">
        <div class="col" style="flex-grow: 0.5">
            <img class="rounded image-profile" src="<?php echo $currentUser->getProfilePicture(300) ?>"/>
            <h1><?php echo $currentUser->getUsername() ?></h1>
            <h2>A member since <?php echo Functions::formatDate($currentUser->getJoinDate()) ?></h2>
            <span>Email : <?php echo $currentUser->getEmail() ?></span>
            <?php
            //display the add to friend button only if the user
            //is logged in and if the profile page does not belong to
            //the logged in user
            if (isset($_SESSION['user_id']) &&
                $currentUser->getUserId() !== $_SESSION['user_id']) {
                ?>
                <form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>" class="mt-3">
                    <button type="submit" name="addToFriendsButton" class="btn btn-primary ">Add to friends</button>
                    <input type="hidden" name="userIdValue"
                           value="<?php echo Functions::encodeWithSha512($currentUser->getUserId()) ?>">
                </form>
                <?php
            }
            ?>
        </div>

        <div class="col-5">
            <?php
            foreach ($userPosts as $post) {
                $view->post = $post;
                include "Views/PostCard.phtml";
            }
            ?>
        </div>
    </div>



    <?php
}
?>

</div>
</body>
</html>
