<?php
include_once "Views/pageElements/Header.phtml";

$currentUser = $view -> currentUser;
$userPosts = $view ->userPosts;
?>
<div class="row">
    <div class="col">
        <img class="rounded image-profile" src="images/nela.jpg">
    </div>
    <div class="col">
        <h1><?php echo $currentUser->getUsername() ?></h1>
        <h2>A member since <?php echo  $currentUser->getJoinDate() ?></h2>
        <span>Email : <?php echo  $currentUser->getEmail() ?></span>
        <form method ="post" action="Friends.php" class="mt-3">
            <button type="submit" name="addToFriendsButton" class="btn btn-primary ">Add to friends</button>
            <input type="hidden" name = "userIdValue"  value ="<?php echo  md5($currentUser->getUserId()) ?>">
        </form>
    </div>
</div>

<div class="row mt-4">
    <div class="col">
        <h2 class="text-center">Here are the posts of this user</h2>
        <?php
          foreach($userPosts as $post){
              $view->post = $post;
              include "Views/PostCard.phtml";
          }
        ?>
    </div>
</div>


</div>
</body>
</html>
