<?php
include_once "Views/pageElements/Header.phtml";

if (isset($view->warningMessage)) {
    include_once "Modals/WarningModal.phtml";
    echo "<script>$('#warningModal').modal('show')</script>";
}

if ($view->currentUser !== null) {
    $currentUser = $view->currentUser;
    $userPosts = $view->userPosts;
    ?>
    <div class="row">
        <div class="col">
            <img class="rounded image-profile" src="<?php echo $currentUser->getProfilePicture() ?>">
        </div>
        <div class="col">
            <h1><?php echo $currentUser->getUsername() ?></h1>
            <h2>A member since <?php echo $currentUser->getJoinDate() ?></h2>
            <span>Email : <?php echo $currentUser->getEmail() ?></span>
            <?php
            //display the add to friend button only if the user
            //is logged in and if the profile page does not belong to
            //the logged in user
            if (isset($_SESSION['user_id']) &&
                $currentUser->getUserId() !== $_SESSION['user_id']) {
                ?>
                <form method="post" action="Friends.php" class="mt-3">
                    <button type="submit" name="addToFriendsButton" class="btn btn-primary ">Add to friends</button>
                    <input type="hidden" name="userIdValue" value="<?php echo md5($currentUser->getUserId()) ?>">
                </form>
                <?php
            }
            ?>

        </div>
    </div>

    <div class="row mt-4">
        <div class="col">
            <h2 class="text-center">Here are the posts of this user</h2>
            <?php
            foreach ($userPosts as $post) {
                $view->post = $post;
                include "Views/PostCard.phtml";
            }
            ?>
        </div>
    </div>
    <?php
}
?>

</div>
</body>
</html>
