<?php include "Views/pageElements/Header.phtml";
?>
<form method="post">
    <!-- Username field -->
    <div class="mt-3">
        <span class="input-label">Username</span>
        <div class="input-group input-group-lg mt-2">
            <input type="text" name="usernameInput" class="form-control"
                   aria-label="Sizing example input"
                   aria-describedby="inputGroup-sizing-default">
        </div>
    </div>

    <!-- Email field -->
    <div class="mt-3">
        <span>Email</span>
        <div class="input-group input-group-lg mt-2">
            <input type="text" name="emailInput" class="form-control" aria-label="Sizing example input"
                   aria-describedby="inputGroup-sizing-default">
        </div>
    </div>

    <!-- Password field -->
    <div class="mt-3">
        <span id="passwordInput">Password</span>
        <div class="input-group input-group-lg mt-2">
            <input type="password" name="passwordInput" class="form-control"
                   aria-label="Sizing example input"
                   aria-describedby="inputGroup-sizing-default">
        </div>
    </div>

    <!-- Confirm Password field -->
    <div class="mt-3">
        <span id="confirmedPasswordInput">Confirm Password</span>
        <div class="input-group input-group-lg mt-2 ">
            <input type="password" name="confirmedPasswordInput" class="form-control"
                   aria-label="Sizing example input"
                   aria-describedby="inputGroup-sizing-default">
        </div>
    </div>

    <div class="mt-3">
        <span>Profile picture</span>
        <div class="custom-file mt-2">
            <input type="file" class="custom-file-input"
                   name="profilePicture" aria-describedby="inputGroupFileAddon01">
            <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
        </div>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-primary" name="registerButton">Register</button>
    </div>
</form>