<?php include_once "Views/pageElements/Header.phtml";

?>
<form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>" enctype="multipart/form-data">
    <!-- Username field -->
    <div class="container-form">
        <div class="form-group">
            <label for="usernameInput">Username</label>
            <div class="input-group input-group-lg mt-2">
                <input type="text" name="usernameInput"
                       id="usernameInput"
                       class="form-control"
                       aria-label="Sizing example input"
                       aria-describedby="inputGroup-sizing-default">
            </div>
        </div>

        <!-- Email field -->
        <div class="form-group">
            <label for="emailInput">Email</label>
            <div class="input-group input-group-lg mt-2">
                <input type="text" name="emailInput"
                       id="emailInput"
                       class="form-control" aria-label="Email Input"
                       aria-describedby="inputGroup-sizing-default">
            </div>
        </div>

        <!-- Password field -->
        <div class="form-group">
            <label for="passwordInput">Password</label>
            <div class="input-group input-group-lg mt-2">
                <input type="password" name="passwordInput"
                       id="passwordInput"
                       class="form-control"
                       aria-label="Password input"
                       aria-describedby="inputGroup-sizing-default">
            </div>
        </div>

        <!-- Confirm Password field -->
        <div class="form-group">
            <label for="confirmedPasswordInput">Confirm Password</label>
            <div class="input-group input-group-lg mt-2 ">
                <input type="password" name="confirmedPasswordInput"
                       id="confirmedPasswordInput"
                       class="form-control"
                       aria-label="Confirm Password Input"
                       aria-describedby="inputGroup-sizing-default">
            </div>
        </div>
        <div class="form-group">
            <label for="profilePicture">Profile picture</label>
            <div class="custom-file mt-2">
                <input type="file" name="profilePicture" id="profilePicture">
            </div>
        </div>
        <div class="mt-3 form-group">
            <img src="Data/Captcha.php" alt=""/>
            <div>
                <input type="text" name="captchaValueEntered"/>
            </div>
        </div>
        <?php if (isset($view->errorMessage)) {
            ?>
            <div class="alert alert-danger mt-3" role="alert">
                <?php echo $view->errorMessage ?>
            </div>
            <?php
        } else {
            if (isset($view->warningMessage)) {
                include_once "Modals/WarningModal.phtml";
                echo "<script>$('#warningModal').modal('show')</script>";
            }
        }
        ?>

        <div class="mt-3">
            <button type="submit" class="btn btn-primary" name="registerButton">Register</button>
        </div>

    </div>
</form>
</div>
</body>
</html>
