<?php
include "Views/pageElements/Header.phtml";
$results = $view->searchResults;
foreach ($results as $post) {
    $view->post = $post;
    ?>

    <div class="row">
        <div class="col">
            <?php include "Views/PostCard.phtml"; ?>
        </div>
    </div>

    <?php
}
if (sizeof($results) == 0) {
    ?>
    <div class="alert alert-secondary mt-5" role="alert">
        We have not found any result for your search ...
    </div>
    <?php
}
?>
</div>
</body>
</html>
