<?php
include "Views/pageElements/Header.phtml";
$favoritePosts = $view->favoritePosts;
?>
<?php
foreach ($favoritePosts as $post) {
    $view->post = $post;
    ?>

    <div class="row">
        <div class="col">
            <?php include "Views/PostCard.phtml"; ?>
        </div>
    </div>

    <?php
}
 if(sizeof($favoritePosts) ==0) {

    ?>
    <div class="alert alert-secondary mt-5" role="alert">
        You do not have any post added to your watch list.
    </div>
    <?php
}
?>


</div>
</body>
</html>
