<?php
include "Views/pageElements/Header.phtml";
if(!isset($_SESSION['user_id'])){
    echo  '<meta http-equiv="refresh"
   content="0; url=index.php">';
}
$favoritePosts = $view->favoritePosts;
?>


    <div class="row">
        <div class="col">
            <?php
            foreach ($favoritePosts as $post) {
            $view->post = $post;
            include "Views/PostCard.phtml";
            }?>
        </div>
    </div>

    <?php
 if(sizeof($favoritePosts) ==0) {

    ?>
    <div class="alert alert-secondary mt-5" role="alert">
        You do not have any post added to your watch list.
    </div>
    <?php
}
?>


</div>
</body>
</html>
