<?php include "Header.phtml";
?>

<h1 class="page-title text-center mt-3">What do you want to include in your post?</h1>
<div class="centered-container" >
<form class="mt-5" method="post" action="AddPost.php" enctype="multipart/form-data">

    <div class="mt-3">
        <label>Title</label>
        <div class="input-group " >
            <input type="text" name="postTitle" class="form-control"
                   aria-describedby="inputGroup-sizing-default">
        </div>
    </div>

    <div class="form-group mt-3">
        <label for="exampleFormControlSelect1">Select Category</label>
        <select class="form-control" name="postCategory">
            <?php
            foreach(getAllCategories() as $category){
                echo '<option>'.$category ->getCategoryName().'</option>';
            }
            ?>
        </select>
    </div>
    <div class="form-group">
        <label >Enter some text</label>
        <textarea class="form-control text-area" name="postContent" rows="3" ></textarea>
    </div>

    <div class="mt-3">
        <label>Post picture</label>
        <div class="custom-file mt-2">
            <input type="file" name="fileToUpload" id="fileToUpload" >
        </div>
    </div>

    <button type="submit" name="addPostButton" class="btn btn-primary mt-3">Add post</button>
</form>
</div>