<!DOCTYPE html>
<html lang="en">
<head>
    <?php include "structure/Header.phtml";?>
    <title>Home</title></head>
<body>
<div class="container mt-3">
    <!-- Content here -->

    <?php
    foreach (getAllPosts() as $post) {
        echo '<div class="card" style="width: 50rem;">';
        echo '<header class="p-3">';
        echo '<h3 >Author : ' . $post->getAuthorName() . '</h3>';
        echo '<h4 class="card-title text-primary">' . $post-> getPostTitle() . '</h4>';
        echo '<h5>' . $post->getPostDate() . '</h5>';
        echo '</header>';
        echo '<img src="images/placeholder.jpg" class="card-img-top" alt="...">';
        echo '<div class="card-body">';
        echo '<p class="card-text">' . $post->getPostContent() . '</p>';
        echo '<a href="structure/Post.phtml" class="btn btn-primary">See post</a>';
        echo '</div></div>';
    }
    ?>
</div>
</body>
</html>