<!DOCTYPE html>
<html lang="en">
<head>
    <?php include "structure/Header.phtml"; ?>
    <title>Home</title></head>
<body>
<div class="container mt-3">
    <?php
    global $warningMessage;
    if ($warningMessage != "") {
        include "structure/WarningModal.phtml";
        echo '<script>$("#warningModal").modal("show")</script>';
    }
    ?>


    <!-- Content here -->
    <h1 class="page-title text-center mb-3">Here are some recent posts</h1>
    <?php
    foreach (getAllPosts() as $post) {
        //todo
        //shouldn't be here ....
        //refactor so that you get the Post.phtml
        //for each object
        echo '<div class="card" style="width: 50rem;margin: auto">';
        echo '<header class="p-3">';
        echo '<h3 >Author : ' . $post->getAuthorName() . '</h3>';
        echo '<h4 class="card-title text-primary">' . $post->getPostTitle() . '</h4>';
        echo '<h5>' . $post->getPostDate() . '</h5>';
        echo '</header>';
        echo '<img src="images/placeholder.jpg" class="card-img-top" alt="...">';
        echo '<div class="card-body">';
        echo '<p class="card-text">' . $post->getPostContent() . '</p>';
        echo '<a href="structure/Post.phtml" class="btn btn-primary">See post</a>';
        echo '</div></div>';
    }
    ?>

</div>
<a href="AddPost.php"
<div class="float" >
    <i  class="fa fa-plus add-button"></i>
</div></a>

</body>

</html>