<form class="form-inline my-2 my-lg-0 mr-4" action="index.php" method="post">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#loginModal">
        Login
    </button>
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">SIGN IN</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <!--Modal body starts here -->
            <div class="modal-body">
                <div class="input-group input-group-lg mt-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="emailSignIn">Email</span>
                    </div>
                    <input type="text" class="form-control" name="emailSignIn" aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default">
                </div>
                <div class="input-group input-group-lg mt-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text"  id="passwordSignIn">Password</span>
                    </div>
                    <input type="password" class="form-control" name = "passwordSignIn"aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default">
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" name="loginButton">Login</button>
            </div>
        </div>
    </div>
</div>
</form>