<form class="form-inline my-2 my-lg-0 mr-4" method="post" >
    <!-- Button trigger modal -->
    <?php
     if(isset($_POST['registerUser'])){
     if(areUserDetailsValid()){
      createUser();
     }else{
         //todo
         //works
       echo '<h1>' . "NOOOOO" . '</h1>';
     }
}

    ?>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#signUpModal">
        Register
    </button>
<!-- Modal -->
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Sign up</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <!--Modal body starts here -->
            <div class="modal-body">
                 <!-- Username field -->
                <div class="mt-3">
                    <span id="usernameInputField">Username</span>
                <div class="input-group input-group-lg m">
                    <input type="text" class="form-control" aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default">
                </div>
                </div>

                <!-- Email field -->
                <div class="mt-3">
                    <span  id="usernameInputField">Email</span>

                <div class="input-group input-group-lg">
                    <input type="text" class="form-control" aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default">
                </div>
                </div>

                <!-- Password field -->
            <div class="mt-3">
                <span  id="passwordInputField">Password</span>
                <div class="input-group input-group-lg">
                    <input type="text" class="form-control" aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default">
                </div>
            </div>

            <!-- Confirm Password field -->
            <div class="mt-3">
                <span id="passwordInputField">Confirm Password</span>
                <div class="input-group input-group-lg ">
                    <input type="text" class="form-control" aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default">
                </div>
            </div>

                <div class="mt-3">
                    <span id="passwordInputField">Profile picture</span>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                    </div>
                </div>



            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" name="registerUser">Login</button>
            </div>
        </div>
    </div>
</div>
</form>