<form class="form-inline my-2 my-lg-0 mr-4" method="post" action="index.php">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#signUpModal">
        Register
    </button>
<!-- Modal -->
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Sign up</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <!--Modal body starts here -->
            <div class="modal-body">
                 <!-- Username field -->
                <div class="mt-3">
                    <span id="usernameInput" class="input-label">Username</span>
                <div class="input-group input-group-lg mt-2">
                    <input type="text" name="usernameInput" class="form-control" aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default">
                </div>
                </div>

                <!-- Email field -->
                <div class="mt-3">
                    <span  id="emailInput">Email</span>

                <div class="input-group input-group-lg mt-2">
                    <input type="text" name="emailInput" class="form-control" aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default">
                </div>
                </div>

                <!-- Password field -->
            <div class="mt-3">
                <span  id="passwordInput">Password</span>
                <div class="input-group input-group-lg mt-2" >
                    <input type="password" name="passwordInput" class="form-control" aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default">
                </div>
            </div>

            <!-- Confirm Password field -->
            <div class="mt-3">
                <span id="confirmedPasswordInput">Confirm Password</span>
                <div class="input-group input-group-lg mt-2 ">
                    <input type="password" name="confirmedPasswordInput" class="form-control" aria-label="Sizing example input"
                           aria-describedby="inputGroup-sizing-default">
                </div>
            </div>

                <div class="mt-3">
                    <span>Profile picture</span>
                    <div class="custom-file mt-2">
                        <input type="file" class="custom-file-input" id="inputGroupFile01" aria-describedby="inputGroupFileAddon01">
                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" name="registerUser">Sign up</button>
            </div>
        </div>
    </div>
</div>

</form>