<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div style="width: 40%;margin: auto" class="mt-5">
<form method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>" onsubmit="return isFormValid()">
                <input type="hidden" value = "<?php echo $view->encryptedEmail; ?>" name="userEmailEncrypted"/>
                <div class="form-group">
                    <label for="newPasswordInput">New password</label>
                    <input type="password" class="form-control" name="newPasswordInput" id="newPasswordInput">
                </div>
                <div class="form-group">
                    <label for="confirmNewPasswordInput">Confirm password</label>
                    <input type="password" class="form-control" id="confirmNewPasswordInput">
                </div>
                <button type="submit" name="submitChangedPassword" class="btn btn-primary">Save changes</button>

    <div class="alert alert-danger" role="alert" style="visibility: hidden;">
    </div
</form>
</div>
<script>
    function isFormValid(){
        let passwordField = document.getElementById("newPasswordInput");
        let confirmedPasswordField = document.getElementById("confirmNewPasswordInput");
        if(passwordField.value.trim() !== confirmedPasswordField.value.trim()){
            let alert = document.getElementsByName("alert alert-danger")[0];
            alert.visibility = "visible";
            alert.innerText = "The passwords must match";
        }
    }
</script>