<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="refresh" content="<?php
     //redirect user to home screen if the login has just happened
    if(isset($view->userJustLoggedIn))echo 0?>; URL='index.php'" />

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/myCSS.css">
    <title><?php $view->pageTitle?></title>

</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="index.php" id="home">Home <span class="sr-only">(current)</span></a>
            </li>
            <?php
            //include options for the profile if the user is logged in
            if ($view->isUserLoggedIn) {
                include "profileOptions.html";
            }
            ?>
        </ul>

    </div>
    <?php
    if (!$view->isUserLoggedIn) {
        ?>
        <a class="btn btn-primary mr-3" href="Login.php" role="button">Sign in</a>
        <a class="btn btn-primary" href="Register.php" role="button">Register</a>
        <?php
    } else {

        ?>
        <form action="index.php" method="post">
            <button type="submit" name="signOutButton" class="btn btn-primary mr-4">
                Sign out
            </button>
        </form>
        <?php

    }
    ?>
</nav>
<div class="container mt-3">
    <?php
    include ("Modals/WarningModal.phtml");
    ?>




