<!DOCTYPE html>
<html lang="en">
<head>
    <title><?php echo $view->pageTitle; ?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="css/myCSS.css">
    <meta name="description" content="Assassins'creed forum. Post tutorials on missions or hidden locations"
    <meta name="keywords" content="Assassin's creed , forum, tutorials"


</head>

<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="index.php">Home <span class="sr-only">(current)</span></a>
                </li>

                <?php
                //include options for the profile if the user is logged in
                if (isset($_SESSION['user_id'])) {

                    ?>
                    <!--List items that should be shown if the user is logged in -->
                    <li class="nav-item">
                        <a class="nav-link" href="MyPosts.php">My Posts <span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="WatchList.php">Watch list <span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="Friends.php">All Friends <span class="sr-only"></span></a>
                    </li>
                    <?php
                }
                ?>

            </ul>

        </div>
        <?php
        if (!isset($_SESSION['user_id'])) {
            ?>
            <a class="btn btn-primary mr-3" href="Login.php" role="button">Login</a>
            <a class="btn btn-primary" href="Register.php" role="button">Register</a>
            <?php
        } else {

            ?>
            <button type="button" data-toggle="modal" data-target="#ConfirmationModal" name="signOutButton"
                    class="btn btn-primary mr-4">
                Sign out
            </button>
            <?php
        }
        ?>
    </nav>
</header>

<div class="container mt-3 mb-3">
    <?php
    include_once "Modals/ConfimationModal.phtml";
    if (isset($view->apiKey)) {
        ?>
        <script>var apiKey = '<?php echo $view->apiKey ?>'</script>
        <?php

    }
    ?>

    <!--Include JQuery in order for bootstrap to properly work
       Getting the files from cache via link is more efficient than actually
       storing them on the server
    -->
    <script src="Javascript/ImageProcessor.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/1766dfddfd.js" crossorigin="anonymous"></script>




