
<form method="post">
<div class="modal" tabindex="-1" role="dialog" id="confirmRemoveModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Warning! You are about to remove a post !</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Do you really want to do that?</p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-danger" name="<?php echo "Remove".$view->postIdToRemove?>" >Remove</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
</form>
