
<form method="post" action="index.php">
<div class="modal" tabindex="-1" role="dialog" id="ConfirmationModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Do you really want to sign out?</p>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-danger" name="signOutButton" >Sign out</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
</form>
