<?php
global $warningMessage;
function displayAlertMessage($message)
{
    $warningMessage = $message;
    ?>

    <div class="modal" tabindex="-1" role="dialog" id="warningModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Warning!!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <?php
                    echo '<p>' . $warningMessage . '</p>';
                    ?>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <?php
    echo '<script>$("#warningModal").modal("show")</script>';
}

?>