<?php
require_once("Api/ApiKeyManager.php");
?>
<form method="get" action="Search.php">
    <div class="input-group md-form form-sm form-2 pl-0 search-box">
        <input class="form-control mr-sm-2" type="search" autocomplete="off" placeholder="Search posts..."
               name="search-posts-field"
               id="search-posts-field"
               aria-label="Search"
               onkeyup="fetchPostSuggestions(this.value)"

        >
        <button type="button" class="btn btn-success mr-2" data-toggle="modal" data-target="#filtersModal">Filters
        </button>
        <div class="input-group-append">
            <button type="submit" class="input-group-text lime lighten-2" name="search-button"><i
                        class="fa fa-search text-grey"
                        aria-hidden="true"></i></button>
        </div>
        <?php
        include_once "Modals/FiltersModal.phtml";
        ?>
        <script src="Javascript/LiveSearch.js"></script>
        <script src="Javascript/ImageProcessor.js"></script>
    </div>

</form>